<?php

namespace app\models;
use Yii;
use yii\base\Model;

class ArizaForm extends Model{

    public $turi;
    public $mablag;

    public function rules()
    {
        return [
            [['mablag'], 'required'],
            ['turi', 'safe'],
        ]; // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return [
            'turi' => 'Yordam turini tanlang :',
            'mablag' => 'Siz uchun kerakli mablag\'ni kiriting (imkon qadar yordam beramiz): '
        ]; // TODO: Change the autogenerated stub
    }

}