<?php

namespace app\models;
use Yii;
use yii\base\Model;

class YordamForm extends Model{

    public $login;
    public $parol;
    public $mablag;

    public function rules()
    {
        return [
            [['login', 'parol', 'mablag'], 'required'],
            ['login', 'string', 'min' => 3, 'max' => 12],
        ]; // TODO: Change the autogenerated stub
    }

}